#!/usr/bin/env python3
"""
Lingshu Knowledge Scout v9.0 - Premium Design Complete
All cards with thumbnails, sorted shortest-first, clean footer, beautiful UI
"""

import os, sys, json, hashlib, re, time, webbrowser
from datetime import datetime, timedelta
from pathlib import Path
from urllib.parse import quote_plus, unquote
from xml.etree import ElementTree as ET

try:
    import requests
except ImportError:
    print("ERROR: pip3 install requests"); sys.exit(1)

SKILL_DIR = Path(os.environ.get("LINGSHU_SKILL_DIR", "/Users/Drip/.trae-cn/skills/lingshu-director"))
SCRIPTS_DIR = SKILL_DIR / "scripts"
CONFIG_PATH = SCRIPTS_DIR / "scout_config.json"
KB_PATH = Path(os.environ.get("LINGSHU_KB_PATH", str(SKILL_DIR / "references" / "knowledge-base.md")))
BRIEFINGS_SRC = Path(os.environ.get("LINGSHU_BRIEFINGS_SRC", str(SKILL_DIR / "references" / "daily-briefings")))
THREE_DAYS_AGO = (datetime.now() - timedelta(days=3)).strftime("%Y-%m-%d")

I18N = {
    "zh": {
        "title": "灵枢·每日简报",
        "download_pdf": "下载 PDF", "lang_switch": "EN", "back": "← 返回",
        "theme_system": "跟随系统", "theme_light": "白天", "theme_dark": "夜晚", "theme_eye": "护眼",
        "footer": "由灵枢生成",
        "paid": "付费", "free": "免费",
        "total_items": "条资讯", "active_cats": "活跃分类", "sources": "数据源",
        "next_push": "下次推送", "generated": "生成时间",
        "sources_list": "GitHub · Hugging Face · 魔搭社区 · Bilibili · YouTube · 微信 · 抖音 · 小红书 · 微博 · TikTok · 头条 · 知乎 · DuckDuckGo · Google News",
        "contact_email": "51323663@qq.com",
        "contact_wechat": "hhzdxtsdd",
    },
    "en": {
        "title": "Lingshu Daily Briefing",
        "download_pdf": "Download PDF", "lang_switch": "中文", "back": "← Back",
        "theme_system": "System", "theme_light": "Light", "theme_dark": "Dark", "theme_eye": "Eye Care",
        "footer": "Generated by Lingshu",
        "paid": "Paid", "free": "Free",
        "total_items": "items", "active_cats": "Active Categories", "sources": "Sources",
        "next_push": "Next push", "generated": "Generated",
        "sources_list": "GitHub · Hugging Face · ModelScope · Bilibili · YouTube · WeChat · Douyin · Xiaohongshu · Weibo · TikTok · Toutiao · Zhihu · DuckDuckGo · Google News",
        "contact_email": "51323663@qq.com",
        "contact_wechat": "hhzdxtsdd",
    }
}

CATEGORIES_ORDER = ["CAT-TREND", "CAT-STYLE", "CAT-TUTORIAL", "CAT-TOOL", "CAT-MODEL", "CAT-WORKFLOW", "CAT-AGENT"]
CATEGORIES = {
    "CAT-TREND":   {"zh": "热点趋势", "en": "热点趋势", "icon": "🔥"},
    "CAT-STYLE":   {"zh": "风格美学", "en": "风格美学", "icon": "🎨"},
    "CAT-TUTORIAL":{"zh": "教程课程", "en": "教程课程", "icon": "📚"},
    "CAT-TOOL":    {"zh": "工具插件", "en": "工具插件", "icon": "🔨"},
    "CAT-MODEL":   {"zh": "模型训练", "en": "模型训练", "icon": "🧠"},
    "CAT-WORKFLOW":{"zh": "工作流", "en": "工作流", "icon": "⚙️"},
    "CAT-AGENT":   {"zh": "Agent", "en": "Agent", "icon": "🤖"},
}
CATEGORY_COLORS = {
    "CAT-TREND":   {"accent": "#ef4444", "accent_light": "#fef2f2", "bg": "#ffffff", "bg2": "#ffffff", "bg3": "#f8f8f8", "border": "#ececec", "text": "#18181b", "text2": "#52525b", "text3": "#a1a1aa"},
    "CAT-STYLE":   {"accent": "#ec4899", "accent_light": "#fdf2f8", "bg": "#ffffff", "bg2": "#ffffff", "bg3": "#f8f8f8", "border": "#ececec", "text": "#18181b", "text2": "#52525b", "text3": "#a1a1aa"},
    "CAT-TUTORIAL":{"accent": "#10b981", "accent_light": "#ecfdf5", "bg": "#ffffff", "bg2": "#ffffff", "bg3": "#f8f8f8", "border": "#ececec", "text": "#18181b", "text2": "#52525b", "text3": "#a1a1aa"},
    "CAT-TOOL":    {"accent": "#f59e0b", "accent_light": "#fffbeb", "bg": "#ffffff", "bg2": "#ffffff", "bg3": "#f8f8f8", "border": "#ececec", "text": "#18181b", "text2": "#52525b", "text3": "#a1a1aa"},
    "CAT-MODEL":   {"accent": "#8b5cf6", "accent_light": "#f5f3ff", "bg": "#ffffff", "bg2": "#ffffff", "bg3": "#f8f8f8", "border": "#ececec", "text": "#18181b", "text2": "#52525b", "text3": "#a1a1aa"},
    "CAT-WORKFLOW":{"accent": "#06b6d4", "accent_light": "#ecfeff", "bg": "#ffffff", "bg2": "#ffffff", "bg3": "#f8f8f8", "border": "#ececec", "text": "#18181b", "text2": "#52525b", "text3": "#a1a1aa"},
    "CAT-AGENT":   {"accent": "#6366f1", "accent_light": "#eef2ff", "bg": "#ffffff", "bg2": "#ffffff", "bg3": "#f8f8f8", "border": "#ececec", "text": "#18181b", "text2": "#52525b", "text3": "#a1a1aa"},
}

def load_config():
    with open(CONFIG_PATH, "r", encoding="utf-8") as f: return json.load(f)

def classify_item(title, desc=""):
    text = f"{title} {desc}".lower()
    best_cat, best_score = "CAT-TREND", 0
    for cat_code in CATEGORIES_ORDER:
        if cat_code not in CATEGORY_KEYWORDS: continue
        score = sum(2 if kw in text else 0 for kw in CATEGORY_KEYWORDS[cat_code])
        if score > best_score: best_score, best_cat = score, cat_code
    return best_cat

def make_dedup_key(title, url):
    return hashlib.md5(f"{title}|{url}".encode("utf-8")).hexdigest()

def load_existing_dedup_keys():
    keys = set()
    if not KB_PATH.exists(): return keys
    with open(KB_PATH, "r", encoding="utf-8") as f:
        for line in f:
            m = re.match(r"^\| ([a-f0-9]{32}) \|", line)
            if m: keys.add(m.group(1))
    return keys

def human_summary(title, desc, source, extra=""):
    smap = {"GitHub": "GitHub", "Hugging Face": "HF", "魔搭社区": "魔搭", "Bilibili": "B站",
            "YouTube": "YouTube", "抖音": "抖音", "小红书": "小红书", "微博": "微博",
            "微信公众号": "微信", "TikTok": "TikTok", "今日头条": "头条", "知乎": "知乎",
            "DuckDuckGo": "搜索", "Google News": "新闻"}
    parts = [smap.get(source, source)]
    if extra: parts.append(extra)
    if desc:
        clean = re.sub(r"[⭐📥▶💰🆓]", "", desc).strip()
        clean = re.sub(r"\s+", " ", clean)[:80]
        if clean: parts.append(clean)
    return " | ".join(parts) if parts else title

def detect_paid(title, desc):
    return any(kw in f"{title} {desc}".lower() for kw in ["paid", "premium", "pro", "subscription", "付费", "会员", "订阅", "$"])

def _extract_ddg_url(raw):
    if "duckduckgo.com/l/?uddg=" in raw:
        m = re.search(r"uddg=([^&]+)", raw)
        if m:
            try: return unquote(m.group(1))
            except: return "https://" + raw.lstrip("/")
    if raw.startswith("//"): return "https://" + raw.lstrip("/")
    return raw if raw.startswith("http") else raw

def is_video(item):
    return item.get("source", "").lower() in ["bilibili", "youtube", "tiktok", "抖音"]

def is_visual_media(item):
    s = item.get("source", "").lower()
    url = item.get("url", "").lower()
    img = item.get("image", "")
    return s in ["bilibili", "youtube", "tiktok", "抖音"] or (img and len(img) > 20 and "thumbnail" not in img.lower()) or any(ext in url for ext in [".mp4", ".webm", ".mov"])

def get_thumbnail_url(source, url, existing_img=""):
    if existing_img and len(existing_img) > 20:
        return existing_img
    s = source.lower()
    if s == "bilibili":
        m = re.search(r'video/(\w+)', url)
        if m: return f"https://i1.hdslb.com/bfs/archive/{m.group(1)}.jpg"
    elif s == "youtube":
        m = re.search(r'v=([\w-]+)', url)
        if m: return f"https://img.youtube.com/vi/{m.group(1)}/hqdefault.jpg"
    elif s in ("tiktok", "抖音"):
        return "https://lf16-tiktok-common.ibytedtos.com/obj/byte-gocso-tcs/tiktok-logo-300x300.png"
    elif "huggingface" in s or "hugging face" in s.lower():
        m = re.search(r'huggingface\.co/([^/]+)', url)
        if m: return f"https://huggingface.co/{m.group(1)}/resolve/main/thumbnail.png"
    elif s in ("google news", "新闻"):
        return "https://www.gstatic.com/images/icons/material/system/1x/news_black_48dp.png"
    elif s == "微博":
        return "https://h5.sinaimg.cn/upload/100/1420/2022/04/25/m_weibo_logo.png"
    elif s == "知乎":
        return "https://static.zhihu.com/heifetz/favicon.ico"
    elif s in ("github", "github trending"):
        m = re.search(r'github\.com/([^/]+)', url)
        if m: return f"https://github.com/{m.group(1)}.png"
    elif s in ("modelscope", "魔搭社区"):
        m = re.search(r'modelscope\.cn/(?:models|datasets)/([^/]+)', url)
        if m: return f"https://modelscope.cn/api/v1/studio/{m.group(1)}/thumbnail"
    return "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/News-icon.png/120px-News-icon.png"

def sort_all_items(items):
    return sorted(items, key=lambda x: len(x.get("description", "")))

CATEGORY_KEYWORDS = {
    "CAT-AGENT": ["agent", "skill", "autonomous", "mcp", "ai agent", "智能体", "agentic"],
    "CAT-WORKFLOW": ["comfyui", "workflow", "pipeline", "automation", "stable diffusion", "工作流"],
    "CAT-MODEL": ["model", "training", "fine-tune", "lora", "checkpoint", "diffusion", "模型", "训练", "llm", "gpt", "claude", "gemini", "deepseek"],
    "CAT-TOOL": ["tool", "plugin", "script", "api", "extension", "sdk", "工具", "插件", "软件"],
    "CAT-TREND": ["trending", "hot", "viral", "breaking", "release", "热点", "趋势", "热门", "news"],
    "CAT-TUTORIAL": ["tutorial", "course", "guide", "how to", "教程", "课程", "入门"],
    "CAT-STYLE": ["style", "aesthetic", "color grade", "visual", "cinematic", "风格", "美学", "调色"],
}

def scout_github(config, keys):
    items = []
    token = config.get("api_keys", {}).get("github_token", "")
    use_api = bool(token and (token.startswith("ghp_") or token.startswith("github_pat_")))
    if use_api:
        headers = {"Accept": "application/vnd.github.v3+json", "Authorization": f"token {token}"}
        for label, q in [("大模型", "LLM large language model"), ("AI Agent", "AI agent framework"), ("ComfyUI", "ComfyUI workflow"), ("AI视频", "AI video generation"), ("AI影视", "AI filmmaking")]:
            try:
                resp = requests.get(f"https://api.github.com/search/repositories?q={quote_plus(q)}&sort=stars&order=desc&per_page=3", headers=headers, timeout=15)
                if resp.status_code != 200: time.sleep(2); continue
                for repo in resp.json().get("items", []):
                    fn, hu = repo.get("full_name", ""), repo.get("html_url", "")
                    if not fn: continue
                    d = (repo.get("description") or "")[:100]
                    s = repo.get("stargazers_count", 0)
                    dk = make_dedup_key(fn, hu)
                    if dk in keys: continue
                    items.append({"title": fn, "url": hu, "description": human_summary(fn, f"[{label}] {d}", "GitHub", f"⭐{s}"),
                                  "source": "GitHub", "category": classify_item(fn, d), "dedup_key": dk,
                                  "image": repo.get("owner", {}).get("avatar_url", ""), "extra": f"⭐{s}", "paid": detect_paid(fn, d)})
                time.sleep(1)
            except: pass
    else:
        ai_kw = ["ai", "agent", "llm", "diffusion", "comfyui", "video", "film", "mcp", "workflow", "gpt", "claude", "gemini", "deepseek", "aigc"]
        seen = set()
        for turl in ["https://github.com/trending?since=daily", "https://github.com/trending/python?since=daily"]:
            try:
                resp = requests.get(turl, headers={"User-Agent": "Mozilla/5.0"}, timeout=15)
                if resp.status_code != 200: continue
                for block in re.findall(r'<article class="Box-row">(.*?)</article>', resp.text, re.DOTALL)[:20]:
                    hm = re.search(r'href="(/[^"]+?)"', block)
                    if not hm: continue
                    fn = hm.group(1).strip("/")
                    if fn in seen or "/" not in fn: continue
                    seen.add(fn)
                    dm = re.search(r'<p class="col-9[^"]*">\s*(.*?)\s*</p>', block, re.DOTALL)
                    d = re.sub(r"<[^>]+>", "", dm.group(1)).strip()[:80] if dm else ""
                    if not any(kw in (fn + " " + d).lower() for kw in ai_kw): continue
                    hu = f"https://github.com/{fn}"
                    dk = make_dedup_key(fn, hu)
                    if dk in keys: continue
                    items.append({"title": fn, "url": hu, "description": human_summary(fn, d, "GitHub", "🔥Trending"),
                                  "source": "GitHub", "category": classify_item(fn, d), "dedup_key": dk,
                                  "image": "", "extra": "🔥Trending", "paid": detect_paid(fn, d)})
                time.sleep(0.5)
            except: pass
    print(f"  GitHub: {len(items)}"); return items

def scout_huggingface(config, keys):
    items, seen = [], set()
    for q in ["text-to-video", "image-generation", "AI filmmaking", "style transfer"]:
        try:
            resp = requests.get(f"https://huggingface.co/api/models?search={quote_plus(q)}&sort=downloads&limit=3", timeout=15)
            if resp.status_code != 200: continue
            for m in resp.json():
                mid = m.get("id", "")
                if mid in seen: continue
                seen.add(mid)
                mu, tags = f"https://huggingface.co/{mid}", m.get("tags", [])
                d = (m.get("pipeline_tag") or "") + " | " + str(tags[:3])
                dk = make_dedup_key(mid, mu)
                if dk in keys: continue
                items.append({"title": mid, "url": mu, "description": human_summary(mid, d, "Hugging Face", f"📥{m.get('downloads',0)}"),
                              "source": "Hugging Face", "category": classify_item(mid, d), "dedup_key": dk,
                              "image": f"https://huggingface.co/{mid}/resolve/main/thumbnail.png", "extra": f"📥{m.get('downloads',0)}", "paid": detect_paid(mid, d)})
            time.sleep(0.5)
        except: pass
    print(f"  Hugging Face: {len(items)}"); return items

def scout_bilibili(config, keys):
    items = []
    for q in ["AI影视制作", "ComfyUI教程", "AI导演", "AIGC短片", "AI视频剪辑"]:
        try:
            resp = requests.get(f"https://api.bilibili.com/x/web-interface/search/type?search_type=video&keyword={quote_plus(q)}&page_size=4&order=pubdate",
                                headers={"User-Agent": "Mozilla/5.0", "Referer": "https://www.bilibili.com"}, timeout=15)
            if resp.status_code != 200: continue
            for v in (resp.json().get("data", {}).get("result", []) or [])[:4]:
                bvid, title = v.get("bvid", ""), re.sub(r"<[^>]+>", "", v.get("title", ""))
                if not bvid: continue
                vu = f"https://www.bilibili.com/video/{bvid}"
                pic = v.get("pic", "")
                if pic and not pic.startswith("http"): pic = "https:" + pic
                d = (v.get("description") or "")[:80]
                dk = make_dedup_key(title, vu)
                if dk in keys: continue
                items.append({"title": title, "url": vu, "description": human_summary(title, d, "Bilibili", f"▶{v.get('play',0)}"),
                              "source": "Bilibili", "category": classify_item(title, d), "dedup_key": dk,
                              "image": pic, "extra": f"▶{v.get('play',0)}", "paid": False})
            time.sleep(0.5)
        except: pass
    print(f"  Bilibili: {len(items)}"); return items

def scout_youtube(config, keys):
    items = []
    for q in ["AI filmmaking 2025", "ComfyUI tutorial", "AI video generation", "AI style transfer"]:
        try:
            resp = requests.get(f"https://www.youtube.com/results?search_query={quote_plus(q)}&sp=CAMSAhAB",
                                headers={"User-Agent": "Mozilla/5.0"}, timeout=15)
            if resp.status_code != 200: continue
            vids = re.findall(r'"videoId":"([a-zA-Z0-9_-]{11})"', resp.text)
            titles = re.findall(r'"title":{"runs":\[{"text":"(.*?)"}\]', resp.text)
            thumbs = re.findall(r'"thumbnails":\[{"url":"(.*?)"', resp.text)
            for i, vid in enumerate(vids[:3]):
                title = (titles[i] if i < len(titles) else f"YouTube {vid}")[:80]
                vu = f"https://www.youtube.com/watch?v={vid}"
                thumb = thumbs[i] if i < len(thumbs) else ""
                if thumb and not thumb.startswith("http"): thumb = "https:" + thumb
                dk = make_dedup_key(title, vu)
                if dk in keys: continue
                items.append({"title": title, "url": vu, "description": human_summary(title, q, "YouTube"),
                              "source": "YouTube", "category": classify_item(title, q), "dedup_key": dk,
                              "image": thumb, "extra": "YouTube", "paid": detect_paid(title, q)})
            time.sleep(1)
        except: pass
    print(f"  YouTube: {len(items)}"); return items

def _fallback(name, queries, keys, aiks=None):
    items = []
    if aiks is None: aiks = ["ai", "AI", "AIGC", "大模型", "GPT", "Claude", "Sora", "DeepSeek", "影视", "视频生成", "智能体"]
    for q in queries:
        try:
            resp = requests.get(f"https://html.duckduckgo.com/html/?q={quote_plus(q)}", headers={"User-Agent": "Mozilla/5.0"}, timeout=15)
            if resp.status_code != 200: continue
            for link, traw in re.findall(r'class="result__a"[^>]*href="([^"]+)"[^>]*>(.*?)</a>', resp.text)[:4]:
                title = re.sub(r"<[^>]+>", "", traw).strip()
                if not title or not link: continue
                if not any(kw in (title + " " + q).lower() for kw in [k.lower() for k in aiks]): continue
                if "duckduckgo.com" in link and "l/?uddg=" not in link: continue
                url = _extract_ddg_url(link)
                if not url or len(url) < 10: continue
                dk = make_dedup_key(title, url)
                if dk in keys: continue
                items.append({"title": title, "url": url, "description": human_summary(title, q, name),
                              "source": name, "category": classify_item(title, q), "dedup_key": dk,
                              "image": "", "extra": name, "paid": detect_paid(title, "")})
            time.sleep(0.5)
        except: pass
    return items

def scout_douyin(config, keys): items = _fallback("抖音", ["抖音 AI影视 最新", "抖音 AIGC 最新"], keys); print(f"  抖音: {len(items)}"); return items
def scout_tiktok(config, keys): items = _fallback("TikTok", ["TikTok AI filmmaking trending", "TikTok AI video effect"], keys, ["ai", "video", "film", "creative"]); print(f"  TikTok: {len(items)}"); return items
def scout_zhihu(config, keys): items = _fallback("知乎", ["知乎 AI 大模型 热门", "知乎 AIGC 工具"], keys); print(f"  知乎: {len(items)}"); return items

def scout_weibo(config, keys):
    items = []
    try:
        resp = requests.get("https://weibo.com/ajax/side/hotSearch", headers={"User-Agent": "Mozilla/5.0"}, timeout=15)
        if resp.status_code == 200:
            for e in resp.json().get("data", {}).get("realtime", [])[:20]:
                word = e.get("word", "") or e.get("note", "")
                if not any(kw in word for kw in ["ai", "AI", "AIGC", "大模型", "GPT", "Claude", "Gemini", "DeepSeek", "Sora", "视频生成", "影视", "智能体"]): continue
                wu = f"https://s.weibo.com/weibo?q={quote_plus(word)}"
                dk = make_dedup_key(word, wu)
                if dk in keys: continue
                items.append({"title": word, "url": wu, "description": human_summary(word, f"微博热搜·{e.get('num',0)}讨论", "微博"),
                              "source": "微博", "category": "CAT-TREND", "dedup_key": dk, "image": "", "extra": f"🔥{e.get('num',0)}", "paid": False})
    except: pass
    if not items: items = _fallback("微博", ["微博 AI 大模型 热点"], keys)
    print(f"  微博: {len(items)}"); return items

def scout_google_news(config, keys):
    items = []
    for q in ["AI filmmaking", "AI agent", "AIGC 工具"]:
        try:
            resp = requests.get(f"https://news.google.com/rss/search?q={quote_plus(q)}&hl=zh-CN&ceid=CN:zh-Hans", headers={"User-Agent": "Mozilla/5.0"}, timeout=15)
            if resp.status_code != 200: continue
            for item in ET.fromstring(resp.text).findall(".//item")[:2]:
                title = (item.find("title").text or "") if item.find("title") is not None else ""
                link = (item.find("link").text or "") if item.find("link") is not None else ""
                pd = (item.find("pubDate").text or "") if item.find("pubDate") is not None else ""
                if not title or not link: continue
                title = re.sub(r" - .+$", "", title).strip()[:80]
                dk = make_dedup_key(title, link)
                if dk in keys: continue
                items.append({"title": title, "url": link, "description": human_summary(title, pd, "Google News"),
                              "source": "Google News", "category": classify_item(title, ""), "dedup_key": dk,
                              "image": "", "extra": pd[:16] if pd else "", "paid": detect_paid(title, "")})
        except: pass
    print(f"  Google News: {len(items)}"); return items

SCOUT_FUNCTIONS = {
    "github": scout_github, "huggingface": scout_huggingface, "bilibili": scout_bilibili, "youtube": scout_youtube,
    "douyin": scout_douyin, "tiktok": scout_tiktok, "weibo": scout_weibo, "zhihu": scout_zhihu,
    "google_news": scout_google_news,
}

# ============ HTML Generation ============

def generate_html(all_items, cat_items, today, now_str, next_date, push_time, page_id, lang, config, is_cat_page=False):
    t = I18N[lang]
    lang_switch_target = "en" if lang == "zh" else "zh"
    total_count = len(all_items)
    active_cats = {c for c in CATEGORIES_ORDER if cat_items.get(c)}
    cc = CATEGORY_COLORS.get(page_id, CATEGORY_COLORS["CAT-TREND"])

    nav_parts = []
    if not is_cat_page:
        nav_parts.append(f'<a href="index_{lang}.html" class="nav active">🏠 总览</a>')
        for ccode in CATEGORIES_ORDER:
            if ccode not in active_cats: continue
            ci = CATEGORIES[ccode]; cnt = len(cat_items.get(ccode, []))
            nav_parts.append(f'<a href="{ccode}_{lang}.html" class="nav">{ci["icon"]} {ci[lang]} ({cnt})</a>')
    else:
        nav_parts.append(f'<a href="index_{lang}.html" class="nav">🏠 总览</a>')
        for ccode in CATEGORIES_ORDER:
            if ccode not in active_cats: continue
            ci = CATEGORIES[ccode]; cnt = len(cat_items.get(ccode, []))
            cls = "nav active" if ccode == page_id else "nav"
            nav_parts.append(f'<a href="{ccode}_{lang}.html" class="{cls}">{ci["icon"]} {ci[lang]} ({cnt})</a>')
    nav_html = "\n".join(nav_parts)

    sections = []
    if is_cat_page:
        ccode = page_id
        items = cat_items.get(ccode, [])
        if not items: return ""
        ci = CATEGORIES[ccode]; name = ci[lang]
        sorted_items = sort_all_items(items)
        cards = ""
        for idx, it in enumerate(sorted_items):
            thumb = get_thumbnail_url(it["source"], it["url"], it.get("image", ""))
            pb = f'<span class="badge paid">💰{t["paid"]}</span>' if it.get("paid") else f'<span class="badge free">🆓{t["free"]}</span>'
            cards += f'''
<article class="card" style="animation-delay:{idx*0.05}s">
<div class="card-cover"><a href="{it["url"]}" target="_blank" rel="noopener"><img src="{thumb}" alt="" loading="lazy" onerror="this.src='';this.parentElement.parentElement.classList.add('no-img')"></a></div>
<div class="card-body">
<h3><a href="{it["url"]}" target="_blank" rel="noopener">{it["title"]}</a></h3>
<div class="card-tags"><span class="tag src">{it["source"]}</span>{pb}</div>
<p class="card-desc">{it["description"]}</p>
<div class="card-meta">{it.get("extra","")}</div>
</div></article>'''
        sections.append(f'''
<section class="section">
<div class="section-hd">
<a href="index_{lang}.html" class="back-btn">{t["back"]}</a>
<span class="s-icon">{ci["icon"]}</span><h2>{name}</h2><em>{len(items)}</em>
</div>
<div class="section-body">{cards}</div>
</section>''')
    else:
        for ccode in CATEGORIES_ORDER:
            items = cat_items.get(ccode, [])
            if not items: continue
            ci = CATEGORIES[ccode]; name = ci[lang]
            sorted_items = sort_all_items(items)
            cards = ""
            for idx, it in enumerate(sorted_items):
                thumb = get_thumbnail_url(it["source"], it["url"], it.get("image", ""))
                pb = f'<span class="badge paid">💰{t["paid"]}</span>' if it.get("paid") else f'<span class="badge free">🆓{t["free"]}</span>'
                cards += f'''
<article class="card" style="animation-delay:{idx*0.05}s">
<div class="card-cover"><a href="{it["url"]}" target="_blank" rel="noopener"><img src="{thumb}" alt="" loading="lazy" onerror="this.src='';this.parentElement.parentElement.classList.add('no-img')"></a></div>
<div class="card-body">
<h3><a href="{it["url"]}" target="_blank" rel="noopener">{it["title"]}</a></h3>
<div class="card-tags"><span class="tag src">{it["source"]}</span><span class="tag cat">{name}</span>{pb}</div>
<p class="card-desc">{it["description"]}</p>
<div class="card-meta">{it.get("extra","")}</div>
</div></article>'''
            sections.append(f'''
<section class="section">
<div class="section-hd"><span class="s-icon">{ci["icon"]}</span><h2>{name}</h2><em>{len(items)}</em></div>
<div class="section-body">{cards}</div>
</section>''')

    bg=cc["bg"];bg2=cc["bg2"];bg3=cc["bg3"];border=cc["border"];tx=cc["text"];tx2=cc["text2"];tx3=cc["text3"];accent=cc["accent"];al=cc["accent_light"]
    darkBg="#0a0a0a";darkBg2="#141414";darkBg3="#1c1c1c";darkBorder="#282828";darkText="#e8e8e8";darkText2="#a0a0a0";darkText3="#666"
    eyeBg="#f0ede0";eyeBg2="#f7f5eb";eyeBg3="#e8e4cc";eyeBorder="#d8d4bc";eyeText="#3a3a2a";eyeText2="#5a5a4a";eyeText3="#8a8a7a"

    css_vars = f'''--bg:{bg};--bg2:{bg2};--bg3:{bg3};--border:{border};--text:{tx};--text2:{tx2};--text3:{tx3};--accent:{accent};--accent-light:{al}'''
    css_dark = f'''--bg:{darkBg};--bg2:{darkBg2};--bg3:{darkBg3};--border:{darkBorder};--text:{darkText};--text2:{darkText2};--text3:{darkText3};--accent:{accent};--accent-light:rgba(255,255,255,0.04)'''
    css_eye = f'''--bg:{eyeBg};--bg2:{eyeBg2};--bg3:{eyeBg3};--border:{eyeBorder};--text:{eyeText};--text2:{eyeText2};--text3:{eyeText3};--accent:{accent};--accent-light:rgba(0,0,0,0.04)'''

    return f'''<!DOCTYPE html>
<html lang="{"zh-CN" if lang=="zh" else "en"}">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>{t["title"]} | {today}</title>
<style>
:root{{{css_vars}}}
[data-theme="dark"]{{{css_dark}}}
[data-theme="eye"]{{{css_eye}}}
*{{margin:0;padding:0;box-sizing:border-box}}
html{{font-size:16px;scroll-behavior:smooth}}
body{{font-family:-apple-system,BlinkMacSystemFont,"Inter","SF Pro Display","Segoe UI",system-ui,sans-serif;background:var(--bg);color:var(--text);line-height:1.6;min-height:100vh;-webkit-font-smoothing:antialiased;opacity:0;animation:fadeIn .3s ease forwards}}
@keyframes fadeIn{{from{{opacity:0}}to{{opacity:1}}}}
@keyframes slideUp{{from{{opacity:0;transform:translateY(10px)}}to{{opacity:1;transform:translateY(0)}}}}

.top{{position:sticky;top:0;z-index:100;background:var(--bg);border-bottom:1px solid var(--border);backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px)}}
.top::before{{content:"";position:absolute;top:0;left:0;right:0;height:2px;background:var(--accent)}}
.top-inner{{max-width:1000px;margin:0 auto;padding:0 20px}}
.top-bar{{display:flex;align-items:center;justify-content:space-between;padding:12px 0 10px;gap:10px}}
.top-title{{font-size:1.05rem;font-weight:700;letter-spacing:-0.03em;white-space:nowrap}}
.top-date{{font-size:.75rem;color:var(--accent);font-weight:500}}
.top-actions{{display:flex;gap:5px;flex-shrink:0}}
.btn{{display:inline-flex;align-items:center;gap:3px;padding:5px 10px;border-radius:6px;font-size:.7rem;font-weight:500;border:1px solid var(--border);background:var(--bg3);color:var(--text);cursor:pointer;transition:all .15s ease;white-space:nowrap;font-family:inherit;outline:none;text-decoration:none}}
.btn:hover{{border-color:var(--accent);color:var(--accent)}}
.btn-primary{{background:var(--accent);color:#fff;border-color:var(--accent)}}
.btn-primary:hover{{opacity:.88;color:#fff}}

.stats{{max-width:1000px;margin:0 auto;padding:8px 20px;display:flex;gap:16px;flex-wrap:wrap;align-items:center}}
.stat{{font-size:.7rem;color:var(--text3);display:flex;align-items:baseline;gap:3px}}
.stat strong{{color:var(--text);font-size:.8rem;font-weight:600;font-variant-numeric:tabular-nums}}

.nav-wrap{{max-width:1000px;margin:0 auto;padding:0 20px 10px}}
.nav{{display:flex;gap:4px;flex-wrap:wrap;overflow-x:auto;-webkit-overflow-scrolling:touch;scrollbar-width:none}}
.nav::-webkit-scrollbar{{display:none}}
.nav a{{display:inline-flex;align-items:center;gap:2px;padding:4px 10px;border-radius:16px;font-size:.68rem;font-weight:500;color:var(--text2);text-decoration:none;white-space:nowrap;transition:all .15s ease;border:1px solid transparent}}
.nav a:hover{{border-color:var(--border);color:var(--text)}}
.nav a.active{{background:var(--accent);color:#fff;border-color:var(--accent)}}

.main{{max-width:1000px;margin:0 auto;padding:20px}}
.section{{margin-bottom:32px}}
.section-hd{{display:flex;align-items:center;gap:8px;padding:8px 0 12px;border-bottom:1px solid var(--border);margin-bottom:14px;flex-wrap:wrap}}
.s-icon{{font-size:1.1rem}}
.section-hd h2{{font-size:.88rem;font-weight:600;flex:1;letter-spacing:-0.01em}}
.section-hd em{{font-size:.62rem;font-style:normal;background:var(--accent);color:#fff;padding:2px 7px;border-radius:10px;font-weight:600}}
.back-btn{{font-size:.72rem;color:var(--text2);text-decoration:none;padding:3px 8px;border-radius:4px;transition:all .15s ease;border:1px solid var(--border);background:var(--bg3);cursor:pointer}}
.back-btn:hover{{color:var(--accent);border-color:var(--accent)}}

.section-body{{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:14px}}
@media(max-width:640px){{.section-body{{grid-template-columns:1fr}}}}

.card{{background:var(--bg2);border:1px solid var(--border);border-radius:10px;overflow:hidden;transition:all .2s cubic-bezier(.4,0,.2,1);animation:slideUp .4s ease both}}
.card:hover{{border-color:var(--accent);box-shadow:0 2px 16px rgba(0,0,0,0.06);transform:translateY(-1px)}}
.card-cover{{position:relative;width:100%;padding-top:56.25%;background:var(--bg3);overflow:hidden}}
.card-cover img{{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;transition:transform .3s ease}}
.card:hover .card-cover img{{transform:scale(1.02)}}
.card.no-img .card-cover{{padding-top:0;height:0;display:none}}
.card.no-img .card-body{{padding-top:16px}}
.card-body{{padding:12px 14px}}
.card-body h3{{font-size:.82rem;font-weight:600;line-height:1.4;letter-spacing:-0.01em;margin-bottom:5px}}
.card-body h3 a{{color:var(--text);text-decoration:none;transition:color .15s ease;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}}
.card-body h3 a:hover{{color:var(--accent)}}
.card-tags{{display:flex;flex-wrap:wrap;gap:3px;margin-bottom:5px;align-items:center}}
.tag{{display:inline-flex;align-items:center;padding:2px 6px;border-radius:3px;font-size:.62rem;font-weight:500;background:var(--bg3);color:var(--text2);white-space:nowrap}}
.src{{background:var(--accent-light);color:var(--accent);font-weight:600}}
.badge{{display:inline-flex;align-items:center;padding:2px 6px;border-radius:3px;font-size:.62rem;font-weight:600}}
.paid{{background:#fef3c7;color:#92400e}}
.free{{background:#d1fae5;color:#065f46}}
.card-desc{{font-size:.76rem;color:var(--text2);line-height:1.5;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;margin-bottom:3px}}
.card-meta{{font-size:.62rem;color:var(--text3);font-weight:500;font-variant-numeric:tabular-nums}}

.footer{{text-align:center;padding:24px 20px;border-top:1px solid var(--border);color:var(--text3);font-size:.65rem}}
.footer-contact-row{{display:flex;align-items:center;justify-content:center;gap:16px;margin-bottom:10px;flex-wrap:wrap}}
.contact-item{{display:inline-flex;align-items:center;gap:6px;padding:6px 14px;border-radius:8px;background:var(--bg3);color:var(--text2);font-size:.72rem;font-weight:500;border:1px solid var(--border);text-decoration:none;transition:all .15s ease}}
.contact-item:hover{{border-color:var(--accent);color:var(--accent)}}
.contact-icon{{width:16px;height:16px;flex-shrink:0}}
.contact-label{{color:var(--text3);font-size:.6rem;margin-right:2px}}
.footer p{{margin:3px 0;line-height:1.6}}

@media print{{
  .top,.nav,.footer,.stats{{display:none!important}}
  body{{background:#fff!important;color:#000!important;font-size:9pt;line-height:1.5}}
  .main{{max-width:100%;padding:0}}
  .section{{margin-bottom:14px;break-after:auto}}
  .section-hd{{padding:5px 0;border-bottom:1px solid #000;margin-bottom:8px}}
  .section-hd h2{{font-size:10pt;color:#000}}
  .section-hd em{{background:#000;color:#fff}}
  .section-body{{grid-template-columns:repeat(2,1fr)!important;gap:8px}}
  .card{{border:1px solid #ccc!important;break-inside:avoid;box-shadow:none!important}}
  .card-cover{{padding-top:50%!important}}
  .card-body h3 a{{color:#000!important;font-size:9pt}}
  .card-desc{{color:#333!important;font-size:8pt;-webkit-line-clamp:2}}
  .tag{{border:1px solid #999!important;background:none!important;color:#333!important}}
  .badge{{border:1px solid #999!important;background:none!important;color:#333!important}}
  @page{{margin:1.5cm;size:A4}}
}}
</style></head>
<body>

<div class="top"><div class="top-inner"><div class="top-bar">
<div><span class="top-title">🎬 {t["title"]}</span> <span class="top-date">{today}</span></div>
<div class="top-actions">
<button class="btn" onclick="switchLang('{lang_switch_target}')">🌐{t["lang_switch"]}</button>
<select class="btn" onchange="setTheme(this.value)"><option value="system">💻{t["theme_system"]}</option><option value="light" selected>☀️{t["theme_light"]}</option><option value="dark">🌙{t["theme_dark"]}</option><option value="eye">👁️{t["theme_eye"]}</option></select>
<button class="btn btn-primary" onclick="window.print()">📄{t["download_pdf"]}</button>
</div></div></div></div>

<div class="stats">
<div class="stat"><strong>{total_count}</strong>{t["total_items"]}</div>
<div class="stat"><strong>{len(active_cats)}</strong>{t["active_cats"]}</div>
<div class="stat"><strong>{len(set(i["source"] for i in all_items))}</strong>{t["sources"]}</div>
</div>

<div class="nav-wrap"><div class="nav">{nav_html}</div></div>

<main class="main">{"\n".join(sections)}</main>

<footer class="footer">
<div class="footer-contact-row">
<a class="contact-item" href="mailto:{t["contact_email"]}">
<svg class="contact-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/></svg>
<span class="contact-label">邮箱</span>{t["contact_email"]}
</a>
<span class="contact-item">
<svg class="contact-icon" viewBox="0 0 24 24" fill="currentColor"><path d="M8.5 11a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm-5 4.5C3.5 12.5 7 9 12 9s8.5 3.5 8.5 6.5c0 1.5-1.5 2.5-3 2.5h-11c-1.5 0-3-1-3-2.5zm15-3a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zM12 2C6.5 2 2 6 2 11c0 3 1.5 5.5 4 7v2h4v-2h4v2h4v-2c2.5-1.5 4-4 4-7 0-5-4.5-9-10-9z"/></svg>
<span class="contact-label">微信</span>{t["contact_wechat"]}
</span>
</div>
<p>{t["footer"]}</p>
<p style="font-size:.6rem;color:var(--text3)">{t["sources_list"]}</p>
<p style="font-size:.6rem">{t["generated"]}: {now_str} &nbsp;|&nbsp; {t["next_push"]}: {next_date} {push_time}</p>
</footer>

<script>
function setTheme(t){{document.documentElement.dataset.theme=t;try{{localStorage.setItem("lingshu-theme",t)}}catch(e){{}}}}
function switchLang(lang){{var u=location.href,f=u.substring(u.lastIndexOf('/')+1),d=u.substring(0,u.lastIndexOf('/')),b=f.replace(/_[a-z]+\\.html$/,'_'+lang+'.html');if(b===f)b=f.replace(/\\.html$/,'_'+lang+'.html');location.href=d+'/'+b}}
(function(){{try{{var s=localStorage.getItem("lingshu-theme");if(s)setTheme(s)}}catch(e){{}}}})();
</script>
</body></html>'''

def generate_all_pages(all_items, today, now_str, next_date, push_time, config):
    custom_dir = config.get("output", {}).get("custom_path", "")
    output_base = Path(custom_dir) if custom_dir else Path("/Users/Drip/Downloads/LingshuBriefings")
    output_base.mkdir(parents=True, exist_ok=True)
    date_dir = output_base / today; date_dir.mkdir(parents=True, exist_ok=True)
    cat_items = {}
    for item in all_items: cat_items.setdefault(item["category"], []).append(item)
    active_cats = {c for c in CATEGORIES_ORDER if cat_items.get(c)}
    for lang in ["zh", "en"]:
        html = generate_html(all_items, cat_items, today, now_str, next_date, push_time, "index", lang, config, is_cat_page=False)
        with open(date_dir / f"index_{lang}.html", "w", encoding="utf-8") as f: f.write(html)
        for ccode in active_cats:
            ch = generate_html(all_items, {ccode: cat_items.get(ccode, [])}, today, now_str, next_date, push_time, ccode, lang, config, is_cat_page=True)
            with open(date_dir / f"{ccode}_{lang}.html", "w", encoding="utf-8") as f: f.write(ch)
    latest = output_base / "latest.html"
    try:
        if latest.exists() or latest.is_symlink(): latest.unlink()
        os.symlink(str(date_dir / "index_zh.html"), str(latest))
    except: pass
    if custom_dir:
        BRIEFINGS_SRC.mkdir(parents=True, exist_ok=True)
        sd = BRIEFINGS_SRC / today
        if not sd.exists():
            try: os.symlink(str(date_dir), str(sd))
            except: pass
    print(f"\n📰 HTML: {date_dir}"); return date_dir / "index_zh.html"

def update_kb(items, today):
    if not items: return
    if not KB_PATH.exists():
        KB_PATH.parent.mkdir(parents=True, exist_ok=True)
        KB_PATH.touch()
    with open(KB_PATH, "r", encoding="utf-8") as f: content = f.read()
    if not content.strip():
        content = "# 灵枢知识库\n\n"
        for ccode in CATEGORIES_ORDER:
            content += f"\n## {ccode}\n<!-- 新条目自动追加在此行下方 -->\n\n"
        content += "\n## 去重索引 (Dedup Index)\n<!-- 格式：MD5(标题+URL) | 采集日期 -->\n"
    seq = max([int(s) for s in re.findall(r"KB-(\d{4})", content)], default=0) + 1
    for item in items:
        cat = item["category"]; marker = f"## {cat}"; idx = content.find(marker)
        if idx == -1: continue
        mi = content.find("<!-- 新条目自动追加在此行下方 -->", idx)
        if mi == -1: continue
        entry = f"| KB-{seq:04d} | {item['title']} | {item['source']} | {item['description'][:60]} | [→]({item['url']}) | {today} |"
        content = content[:mi+len("<!-- 新条目自动追加在此行下方 -->")] + "\n" + entry + content[mi+len("<!-- 新条目自动追加在此行下方 -->"):]
        seq += 1
    di = content.find("## 去重索引")
    if di != -1:
        dmi = content.find("<!-- 格式：MD5(标题+URL) | 采集日期 -->", di)
        if dmi != -1:
            pos = dmi + len("<!-- 格式：MD5(标题+URL) | 采集日期 -->")
            content = content[:pos] + "\n" + "\n".join([f"| {i['dedup_key']} | {today} |" for i in items]) + content[pos:]
    with open(KB_PATH, "w", encoding="utf-8") as f: f.write(content)
    print(f"✅ KB updated: +{len(items)} items")

def main():
    print("="*60); print("🚀 Lingshu Knowledge Scout v9.0 - Premium Design")
    print(f"   {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"); print(f"   3-day filter: since {THREE_DAYS_AGO}"); print("="*60)
    config = load_config(); today = datetime.now().strftime("%Y-%m-%d")
    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    next_date = (datetime.now() + timedelta(days=1)).strftime("%Y-%m-%d")
    push_time = config.get("push_time", "09:00")
    existing_keys = load_existing_dedup_keys(); print(f"   Dedup keys: {len(existing_keys)}")
    enabled = config.get("enabled_sources", list(SCOUT_FUNCTIONS.keys()))
    all_items, seen_urls = [], set()
    for sn in enabled:
        if sn not in SCOUT_FUNCTIONS: print(f"  ⚠️ {sn}"); continue
        print(f"\n🔍 {sn}...")
        try:
            items = SCOUT_FUNCTIONS[sn](config, existing_keys)
            for it in items:
                if it["url"] not in seen_urls: seen_urls.add(it["url"]); all_items.append(it)
        except Exception as e: print(f"  ❌ {sn}: {e}")
    print(f"\n📊 Total: {len(all_items)} new items")
    for ccode in CATEGORIES_ORDER:
        ci = CATEGORIES[ccode]; cnt = sum(1 for i in all_items if i["category"] == ccode)
        if cnt > 0: print(f"   {ci['icon']} {ci['zh']}: {cnt}")
    update_kb(all_items, today)
    BRIEFINGS_SRC.mkdir(parents=True, exist_ok=True)
    mp = BRIEFINGS_SRC / f"{today}.md"
    with open(mp, "w", encoding="utf-8") as f:
        f.write(f"# 灵枢每日简报 | {today}\n\n")
        for ccode in CATEGORIES_ORDER:
            ci = CATEGORIES[ccode]; items = [i for i in all_items if i["category"] == ccode]
            if not items: continue
            f.write(f"\n## {ci['icon']} {ci['zh']}\n\n| # | 标题 | 来源 | 简介 | 链接 |\n|---|------|------|------|------|\n")
            for idx, it in enumerate(items, 1): f.write(f"| {idx} | {it['title']} | {it['source']} | {it['description'][:60]} | [→]({it['url']}) |\n")
    ip = generate_all_pages(all_items, today, now_str, next_date, push_time, config)
    webbrowser.open(f"file://{ip}"); print(f"\n🌐 Opened: {ip}"); print("\n✅ Scout v9.0 complete!")

if __name__ == "__main__": main()
