export type ModelCapability = 'text' | 'image' | 'video' | 'code';

export interface ModelInfo {
  id: string;
  name: string;
  provider: string;
  capabilities: ModelCapability[];
  isFree: boolean;
  pricing?: string;
  description: string;
  maxTokens?: number;
}

export const MODEL_DATABASE: ModelInfo[] = [
  // OpenAI Models
  {
    id: 'o1',
    name: 'o1',
    provider: 'https://api.openai.com/v1',
    capabilities: ['text', 'code'],
    isFree: false,
    pricing: '$15/M input, $60/M output',
    description: 'OpenAI 推理模型，擅长复杂推理和代码',
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'https://api.openai.com/v1',
    capabilities: ['text', 'image'],
    isFree: false,
    pricing: '$2.50/M input, $10/M output',
    description: 'OpenAI 最新旗舰模型，支持文本和图像理解',
    maxTokens: 4096,
  },
  {
    id: 'o1-mini',
    name: 'o1-mini',
    provider: 'https://api.openai.com/v1',
    capabilities: ['text', 'code'],
    isFree: false,
    pricing: '$3/M input, $12/M output',
    description: 'o1 的轻量版本，快速推理',
  },
  {
    id: 'gpt-4-turbo',
    name: 'GPT-4 Turbo',
    provider: 'https://api.openai.com/v1',
    capabilities: ['text'],
    isFree: false,
    pricing: '$10/M input, $30/M output',
    description: 'GPT-4 增强版，支持更大上下文',
    maxTokens: 4096,
  },
  {
    id: 'dall-e-3',
    name: 'DALL-E 3',
    provider: 'https://api.openai.com/v1',
    capabilities: ['image'],
    isFree: false,
    pricing: '$0.04/张 (1024x1024)',
    description: 'OpenAI 图像生成模型',
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'https://api.openai.com/v1',
    capabilities: ['text'],
    isFree: false,
    pricing: '$0.15/M input, $0.60/M output',
    description: 'GPT-4o 的轻量版本，性价比高',
    maxTokens: 4096,
  },

  // Anthropic Models
  {
    id: 'claude-3-5-haiku-latest',
    name: 'Claude 3.5 Haiku',
    provider: 'https://api.anthropic.com/v1',
    capabilities: ['text'],
    isFree: false,
    pricing: '$0.80/M input, $4/M output',
    description: '快速响应的轻量级 Claude 模型',
    maxTokens: 4096,
  },
  {
    id: 'claude-opus-4-20250514',
    name: 'Claude Opus 4',
    provider: 'https://api.anthropic.com/v1',
    capabilities: ['text', 'image'],
    isFree: false,
    pricing: '$15/M input, $75/M output',
    description: 'Anthropic 最强模型，深度分析和创意',
    maxTokens: 4096,
  },
  {
    id: 'claude-sonnet-4-20250514',
    name: 'Claude Sonnet 4',
    provider: 'https://api.anthropic.com/v1',
    capabilities: ['text', 'image'],
    isFree: false,
    pricing: '$3/M input, $15/M output',
    description: '平衡智能与速度的 Claude 模型',
    maxTokens: 4096,
  },

  // Google Gemini Models
  {
    id: 'gemini-1.5-flash',
    name: 'Gemini 1.5 Flash',
    provider: 'https://generativelanguage.googleapis.com/v1beta',
    capabilities: ['text', 'image'],
    isFree: true,
    pricing: '免费',
    description: 'Google 快速多模态模型，免费使用',
    maxTokens: 8192,
  },
  {
    id: 'gemini-1.5-pro',
    name: 'Gemini 1.5 Pro',
    provider: 'https://generativelanguage.googleapis.com/v1beta',
    capabilities: ['text', 'image'],
    isFree: true,
    pricing: '免费',
    description: 'Google 高级多模态模型，1M 上下文',
    maxTokens: 8192,
  },
  {
    id: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'https://generativelanguage.googleapis.com/v1beta',
    capabilities: ['text', 'image'],
    isFree: true,
    pricing: '免费',
    description: 'Google 最新多模态模型，速度快',
    maxTokens: 8192,
  },
  {
    id: 'gemini-2.0-flash-lite',
    name: 'Gemini 2.0 Flash Lite',
    provider: 'https://generativelanguage.googleapis.com/v1beta',
    capabilities: ['text'],
    isFree: true,
    pricing: '免费',
    description: 'Gemini 2.0 Flash 的轻量版本',
    maxTokens: 4096,
  },
  {
    id: 'gemini-2.0-pro-exp-02-05',
    name: 'Gemini 2.0 Pro',
    provider: 'https://generativelanguage.googleapis.com/v1beta',
    capabilities: ['text', 'image'],
    isFree: true,
    pricing: '免费（实验性）',
    description: 'Google 高级多模态推理模型',
    maxTokens: 8192,
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'https://generativelanguage.googleapis.com/v1beta',
    capabilities: ['text', 'image'],
    isFree: true,
    pricing: '免费（实验性）',
    description: 'Google 最新高性价比多模态模型',
    maxTokens: 8192,
  },
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'https://generativelanguage.googleapis.com/v1beta',
    capabilities: ['text', 'image'],
    isFree: true,
    pricing: '免费（实验性）',
    description: 'Google 最强多模态推理模型',
    maxTokens: 8192,
  },

  // DeepSeek Models
  {
    id: 'deepseek-chat',
    name: 'DeepSeek V3',
    provider: 'https://api.deepseek.com/v1',
    capabilities: ['text', 'code'],
    isFree: false,
    pricing: '￥0.27/M input, ￥1.10/M output',
    description: 'DeepSeek 最新聊天模型，性价比高',
    maxTokens: 8192,
  },
  {
    id: 'deepseek-coder',
    name: 'DeepSeek Coder',
    provider: 'https://api.deepseek.com/v1',
    capabilities: ['code'],
    isFree: false,
    pricing: '￥0.27/M input, ￥1.10/M output',
    description: '专用代码生成和理解模型',
    maxTokens: 4096,
  },
  {
    id: 'deepseek-reasoner',
    name: 'DeepSeek Reasoner',
    provider: 'https://api.deepseek.com/v1',
    capabilities: ['text', 'code'],
    isFree: false,
    pricing: '￥0.27/M input, ￥1.10/M output',
    description: 'DeepSeek 推理增强模型',
    maxTokens: 8192,
  },

  // Moonshot Models
  {
    id: 'moonshot-v1-8k',
    name: 'Moonshot V1 8K',
    provider: 'https://api.moonshot.cn/v1',
    capabilities: ['text'],
    isFree: false,
    pricing: '￥12/M tokens',
    description: '月之暗面 Kimi 模型，8K 上下文',
  },
  {
    id: 'moonshot-v1-32k',
    name: 'Moonshot V1 32K',
    provider: 'https://api.moonshot.cn/v1',
    capabilities: ['text'],
    isFree: false,
    pricing: '￥24/M tokens',
    description: '月之暗面 Kimi 模型，32K 长上下文',
  },
  {
    id: 'moonshot-v1-128k',
    name: 'Moonshot V1 128K',
    provider: 'https://api.moonshot.cn/v1',
    capabilities: ['text'],
    isFree: false,
    pricing: '￥60/M tokens',
    description: '月之暗面 Kimi 模型，128K 超长上下文',
  },

  // 智谱 Models
  {
    id: 'glm-4',
    name: 'GLM-4',
    provider: 'https://open.bigmodel.cn/api/paas/v4',
    capabilities: ['text'],
    isFree: false,
    pricing: '￥0.1/1K tokens',
    description: '智谱AI 标准模型，平衡性能和成本',
    maxTokens: 4096,
  },
  {
    id: 'glm-4-flash',
    name: 'GLM-4 Flash',
    provider: 'https://open.bigmodel.cn/api/paas/v4',
    capabilities: ['text'],
    isFree: true,
    pricing: '免费',
    description: '智谱AI 快速响应模型，免费使用',
    maxTokens: 4096,
  },
  {
    id: 'glm-4-air',
    name: 'GLM-4 Air',
    provider: 'https://open.bigmodel.cn/api/paas/v4',
    capabilities: ['text'],
    isFree: true,
    pricing: '免费',
    description: '智谱AI 轻量模型，快速响应，免费',
    maxTokens: 4096,
  },
  {
    id: 'glm-4-plus',
    name: 'GLM-4 Plus',
    provider: 'https://open.bigmodel.cn/api/paas/v4',
    capabilities: ['text'],
    isFree: false,
    pricing: '￥0.05/1K tokens',
    description: '智谱AI 高级推理模型',
    maxTokens: 4096,
  },
  {
    id: 'glm-4v-flash',
    name: 'GLM-4V Flash',
    provider: 'https://open.bigmodel.cn/api/paas/v4',
    capabilities: ['text', 'image'],
    isFree: true,
    pricing: '免费',
    description: '智谱AI 视觉理解模型，免费',
  },
  {
    id: 'glm-4-long',
    name: 'GLM-4 Long',
    provider: 'https://open.bigmodel.cn/api/paas/v4',
    capabilities: ['text'],
    isFree: false,
    pricing: '￥0.05/1K tokens',
    description: '智谱AI 长上下文模型',
    maxTokens: 128000,
  },

  // 通义千问 Models
  {
    id: 'qwen-turbo',
    name: 'Qwen Turbo',
    provider: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    capabilities: ['text'],
    isFree: true,
    pricing: '免费',
    description: '通义千问快速模型，免费使用',
    maxTokens: 8192,
  },
  {
    id: 'qwen-plus',
    name: 'Qwen Plus',
    provider: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    capabilities: ['text'],
    isFree: false,
    pricing: '￥0.008/1K tokens',
    description: '通义千问标准模型，性价比高',
    maxTokens: 8192,
  },
  {
    id: 'qwen-max',
    name: 'Qwen Max',
    provider: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    capabilities: ['text'],
    isFree: false,
    pricing: '￥0.04/1K tokens',
    description: '通义千问最强模型',
    maxTokens: 8192,
  },
  {
    id: 'qwen-long',
    name: 'Qwen Long',
    provider: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    capabilities: ['text'],
    isFree: false,
    pricing: '￥0.001/1K tokens',
    description: '通义千问超长上下文模型',
    maxTokens: 128000,
  },
  {
    id: 'qwen-vl-max',
    name: 'Qwen VL Max',
    provider: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    capabilities: ['text', 'image'],
    isFree: false,
    pricing: '￥0.04/1K tokens',
    description: '通义千问视觉多模态模型',
  },
  {
    id: 'wanx-v1',
    name: '通义万相',
    provider: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    capabilities: ['image'],
    isFree: false,
    pricing: '￥0.04/张',
    description: '阿里图像生成模型',
  },

  // OpenRouter Models
  {
    id: 'openai/gpt-4o',
    name: 'GPT-4o (OpenRouter)',
    provider: 'https://openrouter.ai/api/v1',
    capabilities: ['text', 'image'],
    isFree: false,
    pricing: '按用量计费',
    description: '通过 OpenRouter 访问 GPT-4o',
  },
  {
    id: 'anthropic/claude-sonnet-4',
    name: 'Claude Sonnet 4 (OpenRouter)',
    provider: 'https://openrouter.ai/api/v1',
    capabilities: ['text', 'image'],
    isFree: false,
    pricing: '按用量计费',
    description: '通过 OpenRouter 访问 Claude',
  },
  {
    id: 'google/gemini-2.0-flash-001',
    name: 'Gemini 2.0 Flash (OpenRouter)',
    provider: 'https://openrouter.ai/api/v1',
    capabilities: ['text', 'image'],
    isFree: false,
    pricing: '按用量计费',
    description: '通过 OpenRouter 访问 Gemini',
  },
  {
    id: 'meta-llama/llama-3.1-405b-instruct',
    name: 'Llama 3.1 405B (OpenRouter)',
    provider: 'https://openrouter.ai/api/v1',
    capabilities: ['text'],
    isFree: false,
    pricing: '按用量计费',
    description: '通过 OpenRouter 访问 Llama 3.1',
  },

  // Ollama Models
  {
    id: 'llama3.2',
    name: 'Llama 3.2',
    provider: 'http://localhost:11434/v1',
    capabilities: ['text'],
    isFree: true,
    pricing: '本地运行，完全免费',
    description: 'Meta Llama 3.2 本地运行',
    maxTokens: 4096,
  },
  {
    id: 'llama3.1',
    name: 'Llama 3.1',
    provider: 'http://localhost:11434/v1',
    capabilities: ['text'],
    isFree: true,
    pricing: '本地运行，完全免费',
    description: 'Meta Llama 3.1 本地运行',
    maxTokens: 4096,
  },
  {
    id: 'qwen2.5',
    name: 'Qwen 2.5',
    provider: 'http://localhost:11434/v1',
    capabilities: ['text'],
    isFree: true,
    pricing: '本地运行，完全免费',
    description: '通义千问 2.5 本地运行',
    maxTokens: 4096,
  },
  {
    id: 'mistral',
    name: 'Mistral',
    provider: 'http://localhost:11434/v1',
    capabilities: ['text'],
    isFree: true,
    pricing: '本地运行，完全免费',
    description: 'Mistral AI 模型本地运行',
    maxTokens: 4096,
  },
  {
    id: 'codellama',
    name: 'CodeLlama',
    provider: 'http://localhost:11434/v1',
    capabilities: ['code'],
    isFree: true,
    pricing: '本地运行，完全免费',
    description: 'Meta 代码生成模型本地运行',
    maxTokens: 4096,
  },
  {
    id: 'gemma2',
    name: 'Gemma 2',
    provider: 'http://localhost:11434/v1',
    capabilities: ['text'],
    isFree: true,
    pricing: '本地运行，完全免费',
    description: 'Google Gemma 2 模型本地运行',
    maxTokens: 4096,
  },
  {
    id: 'deepseek-v2',
    name: 'DeepSeek V2',
    provider: 'http://localhost:11434/v1',
    capabilities: ['text', 'code'],
    isFree: true,
    pricing: '本地运行，完全免费',
    description: 'DeepSeek V2 本地运行',
    maxTokens: 4096,
  },
  {
    id: 'phi3',
    name: 'Phi-3',
    provider: 'http://localhost:11434/v1',
    capabilities: ['text'],
    isFree: true,
    pricing: '本地运行，完全免费',
    description: 'Microsoft Phi-3 轻量模型本地运行',
    maxTokens: 4096,
  },

  // LM Studio Models
  {
    id: 'local-model',
    name: '本地模型',
    provider: 'http://localhost:1234/v1',
    capabilities: ['text'],
    isFree: true,
    pricing: '本地运行，完全免费',
    description: 'LM Studio 加载的任意本地模型',
    maxTokens: 4096,
  },

  // LiblibAI Models
  {
    id: 'star-3',
    name: '星流 Star-3',
    provider: 'https://openapi.liblibai.cloud',
    capabilities: ['image'],
    isFree: true,
    pricing: '免费（试用积分）',
    description: '哩布哩布旗舰模型，搭载 LoRA 推荐算法，适合通用风格，无需复杂控制即可生成专业级作品',
  },
  {
    id: 'sdxl',
    name: 'SDXL',
    provider: 'https://openapi.liblibai.cloud',
    capabilities: ['image'],
    isFree: true,
    pricing: '免费（试用积分）',
    description: '基于 Stable Diffusion XL 的开源模型，适合高度自由和精准控制的场景',
  },
  {
    id: 'sd-v1-5',
    name: 'SD 1.5',
    provider: 'https://openapi.liblibai.cloud',
    capabilities: ['image'],
    isFree: true,
    pricing: '免费（试用积分）',
    description: '经典 SD 1.5 模型，快速出图，适合快速原型设计',
  },
];

export function getModelsForProvider(baseURL: string): {
  imageModels: ModelInfo[];
  videoModels: ModelInfo[];
  textModels: ModelInfo[];
  freeModels: ModelInfo[];
} {
  const models = MODEL_DATABASE.filter((m) => m.provider === baseURL);
  return {
    imageModels: models.filter((m) => m.capabilities.includes('image') && !m.capabilities.includes('video')),
    videoModels: models.filter((m) => m.capabilities.includes('video')),
    textModels: models.filter((m) => m.capabilities.includes('text') && !m.capabilities.includes('image') && !m.capabilities.includes('video')),
    freeModels: models.filter((m) => m.isFree),
  };
}

export function getModelInfo(modelId: string): ModelInfo | undefined {
  return MODEL_DATABASE.find((m) => m.id === modelId);
}

export function getCapabilityLabel(capability: ModelCapability): string {
  const labels: Record<ModelCapability, string> = {
    text: '文本',
    image: '图像',
    video: '视频',
    code: '代码',
  };
  return labels[capability];
}
